#!/bin/sh
# Backup Script for my home folder
# 2016-03-27: JG
SERVER="elstar.local"

./start_elstar

if ping -c 1 $SERVER; then
    echo "server live, starting sync..."
    rsync -a -zz --info=progress2 --delete /Users/jangabor/ jan@$SERVER::HomeMirror
else
    echo "server down"
fi 